In [2]:
import pandas as pd
import numpy as np
import math

In [3]:
# Creation of the dataframe and Dropping the useless features
df = pd.read_csv("../Weekly Data/predict_2025_04_05.csv")
df.columns
#df["t2m_predict"].head(10)

Index(['Unnamed: 0', 'number', 'latitude', 'longitude', 'cape', 'sp', 'tcw',
       'sshf', 'slhf', 'msl', 'u10', 'v10', 't2m', 'd2m', 'ssr', 'str', 'ttr',
       'sund', 'skt', 'sm', 'st', 'tcc', 'tp', 'mx2t6', 'mn2t6', 'year',
       'month', 'day', 'dayofweek', 'hour', 'minute', 'second', 't2m_predict',
       'time'],
      dtype='object')

In [4]:
df=df[['time','number','t2m_predict']]

In [5]:
df

                  time  number  t2m_predict
0  2025-04-11 12:00:00     1.0    15.709601
1  2025-04-11 18:00:00    -1.0     8.576655

In [6]:
#df['t2m']=df['t2m']-273.15

In [7]:
# Creation of the results Dataframes which will be made into one df later on
result_t2m  = pd.DataFrame(columns=['forecast_date','target','horizon','q0.025','q0.25','q0.5','q0.75','q0.975'])

In [8]:
times=df.time.unique()
number_of_hours=0
date = "2025-04-11"
row_index=0
for t in times:
  df_=df[df['time']==t]
  t2m = []
  t2m=df_.t2m_predict.values


  horizon = str(number_of_hours)+' hour'
  result_t2m.loc[row_index]  = [date, 't2m', horizon , np.quantile(t2m,0.025),np.quantile(t2m,0.25),np.quantile(t2m,0.5),np.quantile(t2m,0.75),np.quantile(t2m,0.975)]
  row_index=row_index+1
  number_of_hours = number_of_hours + 6

In [9]:
# Dataframes concatination and result exportation
pd.DataFrame.to_csv(result_t2m,"20250405_LowWormwood.csv", index=False)

In [10]:
result_t2m.head(10)

,forecast_date,target,horizon,q0.025,q0.25,q0.5,q0.75,q0.975
0,2025-04-11,t2m,0 hour,15.709601,15.709601,15.709601,15.709601,15.709601
1,2025-04-11,t2m,6 hour,8.576655,8.576655,8.576655,8.576655,8.576655